---
title: "fokontany dash"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{fokontany dash}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# library(SMALLERdash)

library(ggplot2)
library(sf)

library(dplyr)
```

# Load Fokontany Data

```{r}
fkt.poly <- readRDS("data/ifd_fokontany_poly.rds")
mal.data <- readRDS("data/malaria-data.rds")
```

# Time Series of Predictions

```{r}
#join data for this time period

```

Function for time series data

```{r}
timeseries_preds <- function(time_data, pred_dates){
  # time_data <- filter(mal.preds, comm_fkt = 
  # pred_dates <- seq.Date(as.Date("2021-01-01"), as.Date("2021-03-01"), by = "month")
  
  time_data %>%
    mutate(month = lubridate::month(date)) %>%
    mutate(month_label = month.abb[month]) %>%
    mutate(year = lubridate::year(date)) %>%
    #set up order so predictoin is on right
    mutate(month_label = factor(month_label, levels = c(month.abb[4:12], month.abb[1:3]))) %>%
    ggplot(aes(x = month_label)) +
    geom_line(aes(y = median, color = year))
}
```

